/*
 * NetBox API
 * API to access NetBox
 *
 * OpenAPI spec version: 2.5
 * Contact: netbox@digitalocean.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.NestedManufacturer;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Platform
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-11T16:11:54.626-06:00[America/Chicago]")public class Platform {

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("slug")
  private String slug = null;

  @SerializedName("manufacturer")
  private NestedManufacturer manufacturer = null;

  @SerializedName("napalm_driver")
  private String napalmDriver = null;

  @SerializedName("napalm_args")
  private String napalmArgs = null;
  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  public Platform name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public Platform slug(String slug) {
    this.slug = slug;
    return this;
  }

  

  /**
  * Get slug
  * @return slug
  **/
  @Schema(required = true, description = "")
  public String getSlug() {
    return slug;
  }
  public void setSlug(String slug) {
    this.slug = slug;
  }
  public Platform manufacturer(NestedManufacturer manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

  

  /**
  * Get manufacturer
  * @return manufacturer
  **/
  @Schema(description = "")
  public NestedManufacturer getManufacturer() {
    return manufacturer;
  }
  public void setManufacturer(NestedManufacturer manufacturer) {
    this.manufacturer = manufacturer;
  }
  public Platform napalmDriver(String napalmDriver) {
    this.napalmDriver = napalmDriver;
    return this;
  }

  

  /**
  * The name of the NAPALM driver to use when interacting with devices
  * @return napalmDriver
  **/
  @Schema(description = "The name of the NAPALM driver to use when interacting with devices")
  public String getNapalmDriver() {
    return napalmDriver;
  }
  public void setNapalmDriver(String napalmDriver) {
    this.napalmDriver = napalmDriver;
  }
  public Platform napalmArgs(String napalmArgs) {
    this.napalmArgs = napalmArgs;
    return this;
  }

  

  /**
  * Additional arguments to pass when initiating the NAPALM driver (JSON format)
  * @return napalmArgs
  **/
  @Schema(description = "Additional arguments to pass when initiating the NAPALM driver (JSON format)")
  public String getNapalmArgs() {
    return napalmArgs;
  }
  public void setNapalmArgs(String napalmArgs) {
    this.napalmArgs = napalmArgs;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Platform platform = (Platform) o;
    return Objects.equals(this.id, platform.id) &&
        Objects.equals(this.name, platform.name) &&
        Objects.equals(this.slug, platform.slug) &&
        Objects.equals(this.manufacturer, platform.manufacturer) &&
        Objects.equals(this.napalmDriver, platform.napalmDriver) &&
        Objects.equals(this.napalmArgs, platform.napalmArgs);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, name, slug, manufacturer, napalmDriver, napalmArgs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Platform {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    napalmDriver: ").append(toIndentedString(napalmDriver)).append("\n");
    sb.append("    napalmArgs: ").append(toIndentedString(napalmArgs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
