/*
 * NetBox API
 * API to access NetBox
 *
 * OpenAPI spec version: 2.5
 * Contact: netbox@digitalocean.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.NestedDeviceType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * PowerOutletTemplate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-11T16:11:54.626-06:00[America/Chicago]")public class PowerOutletTemplate {

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("device_type")
  private NestedDeviceType deviceType = null;

  @SerializedName("name")
  private String name = null;
  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  public PowerOutletTemplate deviceType(NestedDeviceType deviceType) {
    this.deviceType = deviceType;
    return this;
  }

  

  /**
  * Get deviceType
  * @return deviceType
  **/
  @Schema(required = true, description = "")
  public NestedDeviceType getDeviceType() {
    return deviceType;
  }
  public void setDeviceType(NestedDeviceType deviceType) {
    this.deviceType = deviceType;
  }
  public PowerOutletTemplate name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PowerOutletTemplate powerOutletTemplate = (PowerOutletTemplate) o;
    return Objects.equals(this.id, powerOutletTemplate.id) &&
        Objects.equals(this.deviceType, powerOutletTemplate.deviceType) &&
        Objects.equals(this.name, powerOutletTemplate.name);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, deviceType, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PowerOutletTemplate {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
