/*
 * NetBox API
 * API to access NetBox
 *
 * OpenAPI spec version: 2.5
 * Contact: netbox@digitalocean.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.NestedRole;
import io.swagger.client.model.NestedSite;
import io.swagger.client.model.NestedTenant;
import io.swagger.client.model.NestedVLAN;
import io.swagger.client.model.NestedVRF;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
import org.threeten.bp.OffsetDateTime;

/**
 * Prefix
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-11T16:11:54.626-06:00[America/Chicago]")public class Prefix {

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("family")
  private Integer family = null;

  @SerializedName("prefix")
  private String prefix = null;

  @SerializedName("site")
  private NestedSite site = null;

  @SerializedName("vrf")
  private NestedVRF vrf = null;

  @SerializedName("tenant")
  private NestedTenant tenant = null;

  @SerializedName("vlan")
  private NestedVLAN vlan = null;

  @SerializedName("status")
  private Object status = null;

  @SerializedName("role")
  private NestedRole role = null;

  @SerializedName("is_pool")
  private Boolean isPool = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("tags")
  private List<String> tags = null;

  @SerializedName("custom_fields")
  private Object customFields = null;

  @SerializedName("created")
  private LocalDate created = null;

  @SerializedName("last_updated")
  private OffsetDateTime lastUpdated = null;
  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  /**
  * Get family
  * @return family
  **/
  @Schema(description = "")
  public Integer getFamily() {
    return family;
  }
  public Prefix prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

  

  /**
  * IPv4 or IPv6 network with mask
  * @return prefix
  **/
  @Schema(required = true, description = "IPv4 or IPv6 network with mask")
  public String getPrefix() {
    return prefix;
  }
  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }
  public Prefix site(NestedSite site) {
    this.site = site;
    return this;
  }

  

  /**
  * Get site
  * @return site
  **/
  @Schema(description = "")
  public NestedSite getSite() {
    return site;
  }
  public void setSite(NestedSite site) {
    this.site = site;
  }
  public Prefix vrf(NestedVRF vrf) {
    this.vrf = vrf;
    return this;
  }

  

  /**
  * Get vrf
  * @return vrf
  **/
  @Schema(description = "")
  public NestedVRF getVrf() {
    return vrf;
  }
  public void setVrf(NestedVRF vrf) {
    this.vrf = vrf;
  }
  public Prefix tenant(NestedTenant tenant) {
    this.tenant = tenant;
    return this;
  }

  

  /**
  * Get tenant
  * @return tenant
  **/
  @Schema(description = "")
  public NestedTenant getTenant() {
    return tenant;
  }
  public void setTenant(NestedTenant tenant) {
    this.tenant = tenant;
  }
  public Prefix vlan(NestedVLAN vlan) {
    this.vlan = vlan;
    return this;
  }

  

  /**
  * Get vlan
  * @return vlan
  **/
  @Schema(description = "")
  public NestedVLAN getVlan() {
    return vlan;
  }
  public void setVlan(NestedVLAN vlan) {
    this.vlan = vlan;
  }
  public Prefix status(Object status) {
    this.status = status;
    return this;
  }

  

  /**
  * Get status
  * @return status
  **/
  @Schema(description = "")
  public Object getStatus() {
    return status;
  }
  public void setStatus(Object status) {
    this.status = status;
  }
  public Prefix role(NestedRole role) {
    this.role = role;
    return this;
  }

  

  /**
  * Get role
  * @return role
  **/
  @Schema(description = "")
  public NestedRole getRole() {
    return role;
  }
  public void setRole(NestedRole role) {
    this.role = role;
  }
  public Prefix isPool(Boolean isPool) {
    this.isPool = isPool;
    return this;
  }

  

  /**
  * All IP addresses within this prefix are considered usable
  * @return isPool
  **/
  @Schema(description = "All IP addresses within this prefix are considered usable")
  public Boolean isIsPool() {
    return isPool;
  }
  public void setIsPool(Boolean isPool) {
    this.isPool = isPool;
  }
  public Prefix description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * Get description
  * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public Prefix tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public Prefix addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
  * Get tags
  * @return tags
  **/
  @Schema(description = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }
  public Prefix customFields(Object customFields) {
    this.customFields = customFields;
    return this;
  }

  

  /**
  * Get customFields
  * @return customFields
  **/
  @Schema(description = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }
  /**
  * Get created
  * @return created
  **/
  @Schema(description = "")
  public LocalDate getCreated() {
    return created;
  }
  /**
  * Get lastUpdated
  * @return lastUpdated
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Prefix prefix = (Prefix) o;
    return Objects.equals(this.id, prefix.id) &&
        Objects.equals(this.family, prefix.family) &&
        Objects.equals(this.prefix, prefix.prefix) &&
        Objects.equals(this.site, prefix.site) &&
        Objects.equals(this.vrf, prefix.vrf) &&
        Objects.equals(this.tenant, prefix.tenant) &&
        Objects.equals(this.vlan, prefix.vlan) &&
        Objects.equals(this.status, prefix.status) &&
        Objects.equals(this.role, prefix.role) &&
        Objects.equals(this.isPool, prefix.isPool) &&
        Objects.equals(this.description, prefix.description) &&
        Objects.equals(this.tags, prefix.tags) &&
        Objects.equals(this.customFields, prefix.customFields) &&
        Objects.equals(this.created, prefix.created) &&
        Objects.equals(this.lastUpdated, prefix.lastUpdated);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, family, prefix, site, vrf, tenant, vlan, status, role, isPool, description, tags, customFields, created, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Prefix {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    site: ").append(toIndentedString(site)).append("\n");
    sb.append("    vrf: ").append(toIndentedString(vrf)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    vlan: ").append(toIndentedString(vlan)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    isPool: ").append(toIndentedString(isPool)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
