/*
 * NetBox API
 * API to access NetBox
 *
 * OpenAPI spec version: 2.5
 * Contact: netbox@digitalocean.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.NestedCluster;
import io.swagger.client.model.NestedDeviceRole;
import io.swagger.client.model.NestedIPAddress;
import io.swagger.client.model.NestedPlatform;
import io.swagger.client.model.NestedSite;
import io.swagger.client.model.NestedTenant;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
import org.threeten.bp.OffsetDateTime;

/**
 * VirtualMachineWithConfigContext
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-11T16:11:54.626-06:00[America/Chicago]")public class VirtualMachineWithConfigContext {

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("status")
  private Object status = null;

  @SerializedName("site")
  private NestedSite site = null;

  @SerializedName("cluster")
  private NestedCluster cluster = null;

  @SerializedName("role")
  private NestedDeviceRole role = null;

  @SerializedName("tenant")
  private NestedTenant tenant = null;

  @SerializedName("platform")
  private NestedPlatform platform = null;

  @SerializedName("primary_ip")
  private NestedIPAddress primaryIp = null;

  @SerializedName("primary_ip4")
  private NestedIPAddress primaryIp4 = null;

  @SerializedName("primary_ip6")
  private NestedIPAddress primaryIp6 = null;

  @SerializedName("vcpus")
  private Integer vcpus = null;

  @SerializedName("memory")
  private Integer memory = null;

  @SerializedName("disk")
  private Integer disk = null;

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("local_context_data")
  private String localContextData = null;

  @SerializedName("tags")
  private List<String> tags = null;

  @SerializedName("custom_fields")
  private Object customFields = null;

  @SerializedName("config_context")
  private String configContext = null;

  @SerializedName("created")
  private LocalDate created = null;

  @SerializedName("last_updated")
  private OffsetDateTime lastUpdated = null;
  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  public VirtualMachineWithConfigContext name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public VirtualMachineWithConfigContext status(Object status) {
    this.status = status;
    return this;
  }

  

  /**
  * Get status
  * @return status
  **/
  @Schema(description = "")
  public Object getStatus() {
    return status;
  }
  public void setStatus(Object status) {
    this.status = status;
  }
  public VirtualMachineWithConfigContext site(NestedSite site) {
    this.site = site;
    return this;
  }

  

  /**
  * Get site
  * @return site
  **/
  @Schema(description = "")
  public NestedSite getSite() {
    return site;
  }
  public void setSite(NestedSite site) {
    this.site = site;
  }
  public VirtualMachineWithConfigContext cluster(NestedCluster cluster) {
    this.cluster = cluster;
    return this;
  }

  

  /**
  * Get cluster
  * @return cluster
  **/
  @Schema(required = true, description = "")
  public NestedCluster getCluster() {
    return cluster;
  }
  public void setCluster(NestedCluster cluster) {
    this.cluster = cluster;
  }
  public VirtualMachineWithConfigContext role(NestedDeviceRole role) {
    this.role = role;
    return this;
  }

  

  /**
  * Get role
  * @return role
  **/
  @Schema(description = "")
  public NestedDeviceRole getRole() {
    return role;
  }
  public void setRole(NestedDeviceRole role) {
    this.role = role;
  }
  public VirtualMachineWithConfigContext tenant(NestedTenant tenant) {
    this.tenant = tenant;
    return this;
  }

  

  /**
  * Get tenant
  * @return tenant
  **/
  @Schema(description = "")
  public NestedTenant getTenant() {
    return tenant;
  }
  public void setTenant(NestedTenant tenant) {
    this.tenant = tenant;
  }
  public VirtualMachineWithConfigContext platform(NestedPlatform platform) {
    this.platform = platform;
    return this;
  }

  

  /**
  * Get platform
  * @return platform
  **/
  @Schema(description = "")
  public NestedPlatform getPlatform() {
    return platform;
  }
  public void setPlatform(NestedPlatform platform) {
    this.platform = platform;
  }
  public VirtualMachineWithConfigContext primaryIp(NestedIPAddress primaryIp) {
    this.primaryIp = primaryIp;
    return this;
  }

  

  /**
  * Get primaryIp
  * @return primaryIp
  **/
  @Schema(description = "")
  public NestedIPAddress getPrimaryIp() {
    return primaryIp;
  }
  public void setPrimaryIp(NestedIPAddress primaryIp) {
    this.primaryIp = primaryIp;
  }
  public VirtualMachineWithConfigContext primaryIp4(NestedIPAddress primaryIp4) {
    this.primaryIp4 = primaryIp4;
    return this;
  }

  

  /**
  * Get primaryIp4
  * @return primaryIp4
  **/
  @Schema(description = "")
  public NestedIPAddress getPrimaryIp4() {
    return primaryIp4;
  }
  public void setPrimaryIp4(NestedIPAddress primaryIp4) {
    this.primaryIp4 = primaryIp4;
  }
  public VirtualMachineWithConfigContext primaryIp6(NestedIPAddress primaryIp6) {
    this.primaryIp6 = primaryIp6;
    return this;
  }

  

  /**
  * Get primaryIp6
  * @return primaryIp6
  **/
  @Schema(description = "")
  public NestedIPAddress getPrimaryIp6() {
    return primaryIp6;
  }
  public void setPrimaryIp6(NestedIPAddress primaryIp6) {
    this.primaryIp6 = primaryIp6;
  }
  public VirtualMachineWithConfigContext vcpus(Integer vcpus) {
    this.vcpus = vcpus;
    return this;
  }

  

  /**
  * Get vcpus
  * minimum: 0
  * maximum: 32767
  * @return vcpus
  **/
  @Schema(description = "")
  public Integer getVcpus() {
    return vcpus;
  }
  public void setVcpus(Integer vcpus) {
    this.vcpus = vcpus;
  }
  public VirtualMachineWithConfigContext memory(Integer memory) {
    this.memory = memory;
    return this;
  }

  

  /**
  * Get memory
  * minimum: 0
  * maximum: 2147483647
  * @return memory
  **/
  @Schema(description = "")
  public Integer getMemory() {
    return memory;
  }
  public void setMemory(Integer memory) {
    this.memory = memory;
  }
  public VirtualMachineWithConfigContext disk(Integer disk) {
    this.disk = disk;
    return this;
  }

  

  /**
  * Get disk
  * minimum: 0
  * maximum: 2147483647
  * @return disk
  **/
  @Schema(description = "")
  public Integer getDisk() {
    return disk;
  }
  public void setDisk(Integer disk) {
    this.disk = disk;
  }
  public VirtualMachineWithConfigContext comments(String comments) {
    this.comments = comments;
    return this;
  }

  

  /**
  * Get comments
  * @return comments
  **/
  @Schema(description = "")
  public String getComments() {
    return comments;
  }
  public void setComments(String comments) {
    this.comments = comments;
  }
  public VirtualMachineWithConfigContext localContextData(String localContextData) {
    this.localContextData = localContextData;
    return this;
  }

  

  /**
  * Get localContextData
  * @return localContextData
  **/
  @Schema(description = "")
  public String getLocalContextData() {
    return localContextData;
  }
  public void setLocalContextData(String localContextData) {
    this.localContextData = localContextData;
  }
  public VirtualMachineWithConfigContext tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public VirtualMachineWithConfigContext addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
  * Get tags
  * @return tags
  **/
  @Schema(description = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }
  public VirtualMachineWithConfigContext customFields(Object customFields) {
    this.customFields = customFields;
    return this;
  }

  

  /**
  * Get customFields
  * @return customFields
  **/
  @Schema(description = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }
  /**
  * Get configContext
  * @return configContext
  **/
  @Schema(description = "")
  public String getConfigContext() {
    return configContext;
  }
  /**
  * Get created
  * @return created
  **/
  @Schema(description = "")
  public LocalDate getCreated() {
    return created;
  }
  /**
  * Get lastUpdated
  * @return lastUpdated
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualMachineWithConfigContext virtualMachineWithConfigContext = (VirtualMachineWithConfigContext) o;
    return Objects.equals(this.id, virtualMachineWithConfigContext.id) &&
        Objects.equals(this.name, virtualMachineWithConfigContext.name) &&
        Objects.equals(this.status, virtualMachineWithConfigContext.status) &&
        Objects.equals(this.site, virtualMachineWithConfigContext.site) &&
        Objects.equals(this.cluster, virtualMachineWithConfigContext.cluster) &&
        Objects.equals(this.role, virtualMachineWithConfigContext.role) &&
        Objects.equals(this.tenant, virtualMachineWithConfigContext.tenant) &&
        Objects.equals(this.platform, virtualMachineWithConfigContext.platform) &&
        Objects.equals(this.primaryIp, virtualMachineWithConfigContext.primaryIp) &&
        Objects.equals(this.primaryIp4, virtualMachineWithConfigContext.primaryIp4) &&
        Objects.equals(this.primaryIp6, virtualMachineWithConfigContext.primaryIp6) &&
        Objects.equals(this.vcpus, virtualMachineWithConfigContext.vcpus) &&
        Objects.equals(this.memory, virtualMachineWithConfigContext.memory) &&
        Objects.equals(this.disk, virtualMachineWithConfigContext.disk) &&
        Objects.equals(this.comments, virtualMachineWithConfigContext.comments) &&
        Objects.equals(this.localContextData, virtualMachineWithConfigContext.localContextData) &&
        Objects.equals(this.tags, virtualMachineWithConfigContext.tags) &&
        Objects.equals(this.customFields, virtualMachineWithConfigContext.customFields) &&
        Objects.equals(this.configContext, virtualMachineWithConfigContext.configContext) &&
        Objects.equals(this.created, virtualMachineWithConfigContext.created) &&
        Objects.equals(this.lastUpdated, virtualMachineWithConfigContext.lastUpdated);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, name, status, site, cluster, role, tenant, platform, primaryIp, primaryIp4, primaryIp6, vcpus, memory, disk, comments, localContextData, tags, customFields, configContext, created, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualMachineWithConfigContext {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    site: ").append(toIndentedString(site)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    primaryIp: ").append(toIndentedString(primaryIp)).append("\n");
    sb.append("    primaryIp4: ").append(toIndentedString(primaryIp4)).append("\n");
    sb.append("    primaryIp6: ").append(toIndentedString(primaryIp6)).append("\n");
    sb.append("    vcpus: ").append(toIndentedString(vcpus)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    disk: ").append(toIndentedString(disk)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    localContextData: ").append(toIndentedString(localContextData)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    configContext: ").append(toIndentedString(configContext)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
