/*
 * NetBox API
 * API to access NetBox
 *
 * OpenAPI spec version: 2.5
 * Contact: netbox@digitalocean.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
import org.threeten.bp.OffsetDateTime;

/**
 * WritableCircuit
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-11T16:11:54.626-06:00[America/Chicago]")public class WritableCircuit {

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("cid")
  private String cid = null;

  @SerializedName("provider")
  private Integer provider = null;

  @SerializedName("type")
  private Integer type = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("tenant")
  private Integer tenant = null;

  @SerializedName("install_date")
  private LocalDate installDate = null;

  @SerializedName("commit_rate")
  private Integer commitRate = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("tags")
  private List<String> tags = null;

  @SerializedName("custom_fields")
  private Object customFields = null;

  @SerializedName("created")
  private LocalDate created = null;

  @SerializedName("last_updated")
  private OffsetDateTime lastUpdated = null;
  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  public WritableCircuit cid(String cid) {
    this.cid = cid;
    return this;
  }

  

  /**
  * Get cid
  * @return cid
  **/
  @Schema(required = true, description = "")
  public String getCid() {
    return cid;
  }
  public void setCid(String cid) {
    this.cid = cid;
  }
  public WritableCircuit provider(Integer provider) {
    this.provider = provider;
    return this;
  }

  

  /**
  * Get provider
  * @return provider
  **/
  @Schema(required = true, description = "")
  public Integer getProvider() {
    return provider;
  }
  public void setProvider(Integer provider) {
    this.provider = provider;
  }
  public WritableCircuit type(Integer type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(required = true, description = "")
  public Integer getType() {
    return type;
  }
  public void setType(Integer type) {
    this.type = type;
  }
  public WritableCircuit status(Integer status) {
    this.status = status;
    return this;
  }

  

  /**
  * Get status
  * @return status
  **/
  @Schema(description = "")
  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }
  public WritableCircuit tenant(Integer tenant) {
    this.tenant = tenant;
    return this;
  }

  

  /**
  * Get tenant
  * @return tenant
  **/
  @Schema(description = "")
  public Integer getTenant() {
    return tenant;
  }
  public void setTenant(Integer tenant) {
    this.tenant = tenant;
  }
  public WritableCircuit installDate(LocalDate installDate) {
    this.installDate = installDate;
    return this;
  }

  

  /**
  * Get installDate
  * @return installDate
  **/
  @Schema(description = "")
  public LocalDate getInstallDate() {
    return installDate;
  }
  public void setInstallDate(LocalDate installDate) {
    this.installDate = installDate;
  }
  public WritableCircuit commitRate(Integer commitRate) {
    this.commitRate = commitRate;
    return this;
  }

  

  /**
  * Get commitRate
  * minimum: 0
  * maximum: 2147483647
  * @return commitRate
  **/
  @Schema(description = "")
  public Integer getCommitRate() {
    return commitRate;
  }
  public void setCommitRate(Integer commitRate) {
    this.commitRate = commitRate;
  }
  public WritableCircuit description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * Get description
  * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public WritableCircuit comments(String comments) {
    this.comments = comments;
    return this;
  }

  

  /**
  * Get comments
  * @return comments
  **/
  @Schema(description = "")
  public String getComments() {
    return comments;
  }
  public void setComments(String comments) {
    this.comments = comments;
  }
  public WritableCircuit tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public WritableCircuit addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
  * Get tags
  * @return tags
  **/
  @Schema(description = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }
  public WritableCircuit customFields(Object customFields) {
    this.customFields = customFields;
    return this;
  }

  

  /**
  * Get customFields
  * @return customFields
  **/
  @Schema(description = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }
  /**
  * Get created
  * @return created
  **/
  @Schema(description = "")
  public LocalDate getCreated() {
    return created;
  }
  /**
  * Get lastUpdated
  * @return lastUpdated
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WritableCircuit writableCircuit = (WritableCircuit) o;
    return Objects.equals(this.id, writableCircuit.id) &&
        Objects.equals(this.cid, writableCircuit.cid) &&
        Objects.equals(this.provider, writableCircuit.provider) &&
        Objects.equals(this.type, writableCircuit.type) &&
        Objects.equals(this.status, writableCircuit.status) &&
        Objects.equals(this.tenant, writableCircuit.tenant) &&
        Objects.equals(this.installDate, writableCircuit.installDate) &&
        Objects.equals(this.commitRate, writableCircuit.commitRate) &&
        Objects.equals(this.description, writableCircuit.description) &&
        Objects.equals(this.comments, writableCircuit.comments) &&
        Objects.equals(this.tags, writableCircuit.tags) &&
        Objects.equals(this.customFields, writableCircuit.customFields) &&
        Objects.equals(this.created, writableCircuit.created) &&
        Objects.equals(this.lastUpdated, writableCircuit.lastUpdated);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, cid, provider, type, status, tenant, installDate, commitRate, description, comments, tags, customFields, created, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WritableCircuit {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    installDate: ").append(toIndentedString(installDate)).append("\n");
    sb.append("    commitRate: ").append(toIndentedString(commitRate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
