/*
 * NetBox API
 * API to access NetBox
 *
 * OpenAPI spec version: 2.5
 * Contact: netbox@digitalocean.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * WritableFrontPortTemplate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-11T16:11:54.626-06:00[America/Chicago]")public class WritableFrontPortTemplate {

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("device_type")
  private Integer deviceType = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private Integer type = null;

  @SerializedName("rear_port")
  private Integer rearPort = null;

  @SerializedName("rear_port_position")
  private Integer rearPortPosition = null;
  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  public WritableFrontPortTemplate deviceType(Integer deviceType) {
    this.deviceType = deviceType;
    return this;
  }

  

  /**
  * Get deviceType
  * @return deviceType
  **/
  @Schema(required = true, description = "")
  public Integer getDeviceType() {
    return deviceType;
  }
  public void setDeviceType(Integer deviceType) {
    this.deviceType = deviceType;
  }
  public WritableFrontPortTemplate name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public WritableFrontPortTemplate type(Integer type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(required = true, description = "")
  public Integer getType() {
    return type;
  }
  public void setType(Integer type) {
    this.type = type;
  }
  public WritableFrontPortTemplate rearPort(Integer rearPort) {
    this.rearPort = rearPort;
    return this;
  }

  

  /**
  * Get rearPort
  * @return rearPort
  **/
  @Schema(required = true, description = "")
  public Integer getRearPort() {
    return rearPort;
  }
  public void setRearPort(Integer rearPort) {
    this.rearPort = rearPort;
  }
  public WritableFrontPortTemplate rearPortPosition(Integer rearPortPosition) {
    this.rearPortPosition = rearPortPosition;
    return this;
  }

  

  /**
  * Get rearPortPosition
  * minimum: 1
  * maximum: 64
  * @return rearPortPosition
  **/
  @Schema(description = "")
  public Integer getRearPortPosition() {
    return rearPortPosition;
  }
  public void setRearPortPosition(Integer rearPortPosition) {
    this.rearPortPosition = rearPortPosition;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WritableFrontPortTemplate writableFrontPortTemplate = (WritableFrontPortTemplate) o;
    return Objects.equals(this.id, writableFrontPortTemplate.id) &&
        Objects.equals(this.deviceType, writableFrontPortTemplate.deviceType) &&
        Objects.equals(this.name, writableFrontPortTemplate.name) &&
        Objects.equals(this.type, writableFrontPortTemplate.type) &&
        Objects.equals(this.rearPort, writableFrontPortTemplate.rearPort) &&
        Objects.equals(this.rearPortPosition, writableFrontPortTemplate.rearPortPosition);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, deviceType, name, type, rearPort, rearPortPosition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WritableFrontPortTemplate {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    rearPort: ").append(toIndentedString(rearPort)).append("\n");
    sb.append("    rearPortPosition: ").append(toIndentedString(rearPortPosition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
