/*
 * NetBox API
 * API to access NetBox
 *
 * OpenAPI spec version: 2.5
 * Contact: netbox@digitalocean.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
import org.threeten.bp.OffsetDateTime;

/**
 * WritablePrefix
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-11T16:11:54.626-06:00[America/Chicago]")public class WritablePrefix {

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("family")
  private Integer family = null;

  @SerializedName("prefix")
  private String prefix = null;

  @SerializedName("site")
  private Integer site = null;

  @SerializedName("vrf")
  private Integer vrf = null;

  @SerializedName("tenant")
  private Integer tenant = null;

  @SerializedName("vlan")
  private Integer vlan = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("role")
  private Integer role = null;

  @SerializedName("is_pool")
  private Boolean isPool = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("tags")
  private List<String> tags = null;

  @SerializedName("custom_fields")
  private Object customFields = null;

  @SerializedName("created")
  private LocalDate created = null;

  @SerializedName("last_updated")
  private OffsetDateTime lastUpdated = null;
  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  /**
  * Get family
  * @return family
  **/
  @Schema(description = "")
  public Integer getFamily() {
    return family;
  }
  public WritablePrefix prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

  

  /**
  * IPv4 or IPv6 network with mask
  * @return prefix
  **/
  @Schema(required = true, description = "IPv4 or IPv6 network with mask")
  public String getPrefix() {
    return prefix;
  }
  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }
  public WritablePrefix site(Integer site) {
    this.site = site;
    return this;
  }

  

  /**
  * Get site
  * @return site
  **/
  @Schema(description = "")
  public Integer getSite() {
    return site;
  }
  public void setSite(Integer site) {
    this.site = site;
  }
  public WritablePrefix vrf(Integer vrf) {
    this.vrf = vrf;
    return this;
  }

  

  /**
  * Get vrf
  * @return vrf
  **/
  @Schema(description = "")
  public Integer getVrf() {
    return vrf;
  }
  public void setVrf(Integer vrf) {
    this.vrf = vrf;
  }
  public WritablePrefix tenant(Integer tenant) {
    this.tenant = tenant;
    return this;
  }

  

  /**
  * Get tenant
  * @return tenant
  **/
  @Schema(description = "")
  public Integer getTenant() {
    return tenant;
  }
  public void setTenant(Integer tenant) {
    this.tenant = tenant;
  }
  public WritablePrefix vlan(Integer vlan) {
    this.vlan = vlan;
    return this;
  }

  

  /**
  * Get vlan
  * @return vlan
  **/
  @Schema(description = "")
  public Integer getVlan() {
    return vlan;
  }
  public void setVlan(Integer vlan) {
    this.vlan = vlan;
  }
  public WritablePrefix status(Integer status) {
    this.status = status;
    return this;
  }

  

  /**
  * Operational status of this prefix
  * @return status
  **/
  @Schema(description = "Operational status of this prefix")
  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }
  public WritablePrefix role(Integer role) {
    this.role = role;
    return this;
  }

  

  /**
  * The primary function of this prefix
  * @return role
  **/
  @Schema(description = "The primary function of this prefix")
  public Integer getRole() {
    return role;
  }
  public void setRole(Integer role) {
    this.role = role;
  }
  public WritablePrefix isPool(Boolean isPool) {
    this.isPool = isPool;
    return this;
  }

  

  /**
  * All IP addresses within this prefix are considered usable
  * @return isPool
  **/
  @Schema(description = "All IP addresses within this prefix are considered usable")
  public Boolean isIsPool() {
    return isPool;
  }
  public void setIsPool(Boolean isPool) {
    this.isPool = isPool;
  }
  public WritablePrefix description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * Get description
  * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public WritablePrefix tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public WritablePrefix addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
  * Get tags
  * @return tags
  **/
  @Schema(description = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }
  public WritablePrefix customFields(Object customFields) {
    this.customFields = customFields;
    return this;
  }

  

  /**
  * Get customFields
  * @return customFields
  **/
  @Schema(description = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }
  /**
  * Get created
  * @return created
  **/
  @Schema(description = "")
  public LocalDate getCreated() {
    return created;
  }
  /**
  * Get lastUpdated
  * @return lastUpdated
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WritablePrefix writablePrefix = (WritablePrefix) o;
    return Objects.equals(this.id, writablePrefix.id) &&
        Objects.equals(this.family, writablePrefix.family) &&
        Objects.equals(this.prefix, writablePrefix.prefix) &&
        Objects.equals(this.site, writablePrefix.site) &&
        Objects.equals(this.vrf, writablePrefix.vrf) &&
        Objects.equals(this.tenant, writablePrefix.tenant) &&
        Objects.equals(this.vlan, writablePrefix.vlan) &&
        Objects.equals(this.status, writablePrefix.status) &&
        Objects.equals(this.role, writablePrefix.role) &&
        Objects.equals(this.isPool, writablePrefix.isPool) &&
        Objects.equals(this.description, writablePrefix.description) &&
        Objects.equals(this.tags, writablePrefix.tags) &&
        Objects.equals(this.customFields, writablePrefix.customFields) &&
        Objects.equals(this.created, writablePrefix.created) &&
        Objects.equals(this.lastUpdated, writablePrefix.lastUpdated);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, family, prefix, site, vrf, tenant, vlan, status, role, isPool, description, tags, customFields, created, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WritablePrefix {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    site: ").append(toIndentedString(site)).append("\n");
    sb.append("    vrf: ").append(toIndentedString(vrf)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    vlan: ").append(toIndentedString(vlan)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    isPool: ").append(toIndentedString(isPool)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
