/*
 * NetBox API
 * API to access NetBox
 *
 * OpenAPI spec version: 2.5
 * Contact: netbox@digitalocean.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
import org.threeten.bp.OffsetDateTime;

/**
 * WritableAggregate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-11T16:11:54.626-06:00[America/Chicago]")public class WritableAggregate {

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("family")
  private Integer family = null;

  @SerializedName("prefix")
  private String prefix = null;

  @SerializedName("rir")
  private Integer rir = null;

  @SerializedName("date_added")
  private LocalDate dateAdded = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("tags")
  private List<String> tags = null;

  @SerializedName("custom_fields")
  private Object customFields = null;

  @SerializedName("created")
  private LocalDate created = null;

  @SerializedName("last_updated")
  private OffsetDateTime lastUpdated = null;
  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  /**
  * Get family
  * @return family
  **/
  @Schema(description = "")
  public Integer getFamily() {
    return family;
  }
  public WritableAggregate prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

  

  /**
  * Get prefix
  * @return prefix
  **/
  @Schema(required = true, description = "")
  public String getPrefix() {
    return prefix;
  }
  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }
  public WritableAggregate rir(Integer rir) {
    this.rir = rir;
    return this;
  }

  

  /**
  * Get rir
  * @return rir
  **/
  @Schema(required = true, description = "")
  public Integer getRir() {
    return rir;
  }
  public void setRir(Integer rir) {
    this.rir = rir;
  }
  public WritableAggregate dateAdded(LocalDate dateAdded) {
    this.dateAdded = dateAdded;
    return this;
  }

  

  /**
  * Get dateAdded
  * @return dateAdded
  **/
  @Schema(description = "")
  public LocalDate getDateAdded() {
    return dateAdded;
  }
  public void setDateAdded(LocalDate dateAdded) {
    this.dateAdded = dateAdded;
  }
  public WritableAggregate description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * Get description
  * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public WritableAggregate tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public WritableAggregate addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
  * Get tags
  * @return tags
  **/
  @Schema(description = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }
  public WritableAggregate customFields(Object customFields) {
    this.customFields = customFields;
    return this;
  }

  

  /**
  * Get customFields
  * @return customFields
  **/
  @Schema(description = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }
  /**
  * Get created
  * @return created
  **/
  @Schema(description = "")
  public LocalDate getCreated() {
    return created;
  }
  /**
  * Get lastUpdated
  * @return lastUpdated
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WritableAggregate writableAggregate = (WritableAggregate) o;
    return Objects.equals(this.id, writableAggregate.id) &&
        Objects.equals(this.family, writableAggregate.family) &&
        Objects.equals(this.prefix, writableAggregate.prefix) &&
        Objects.equals(this.rir, writableAggregate.rir) &&
        Objects.equals(this.dateAdded, writableAggregate.dateAdded) &&
        Objects.equals(this.description, writableAggregate.description) &&
        Objects.equals(this.tags, writableAggregate.tags) &&
        Objects.equals(this.customFields, writableAggregate.customFields) &&
        Objects.equals(this.created, writableAggregate.created) &&
        Objects.equals(this.lastUpdated, writableAggregate.lastUpdated);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, family, prefix, rir, dateAdded, description, tags, customFields, created, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WritableAggregate {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    rir: ").append(toIndentedString(rir)).append("\n");
    sb.append("    dateAdded: ").append(toIndentedString(dateAdded)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
